### ISSUE TITLE
Reviewing the project

### ISSUE THREAD

**Issue by boniface193** [til2to/my-portfolio#9]
Hi, @til2to 

your project is ok, there is nothing else to be done there
but just an advice, You should use a class if you need to use the same selector more than once within a page or a site, instead of an ID selector
![133696182-6c5b784b-0083-427a-b24d-3ec870915f79](https://user-images.githubusercontent.com/19141170/207257568-9207b40d-28cb-4d1c-8608-226822675312.jpg)

**Comment by til2to** [comment]
😄
